### ISSUE TITLE
[4pt] Select/Pairs: Partial results

### ISSUE THREAD

**Issue by dokshina** [tarantool/crud#117]
The second and complex part of #53

**Comment by AnaNek** [comment]
## Summary

Ability to add fields option for select function. Fields option allows to get only a subset of fields. 

## Motivation 

Sending only a subset of fields can reduce the network load.

## Possible implementation

Select function gets tuples from all storages and compare it by index on router. Filtering fields on storage can lead to the loss of indexed fields (search indexes to iterate over), which makes it impossible for further iteration and comparison on router. Default iteration index is primary index. We could keep primary index fields in storage result even if these fields are not specified in fields parameter. If storage result includes scan index then it possible to use scan index for comparison tuples on router. Otherwise we still have primary index in storage result for iterate over on router.
