### ISSUE TITLE
Add new flag "return nothing" in options for DML operations

### ISSUE THREAD

**Issue by wey1and** [tarantool/crud#267]
It is necessary to add the "return nothing" flag to the options of such functions as: truncate(), replace(), etc. Where the return of a function is not so important, but performance may be required.

The same was in TDG2 https://github.com/tarantool/tdg2/issues/1450

**Comment by Totktonada** [comment]
It is especially important for `crud.*_many()` operations (see PR #232). I propose `noreturn` name.

**Comment by DifferentialOrange** [comment]
There is a question about what exactly "no value" value is. let's discuss existing API first.

Core Tarantool `space:upsert` does not return any values with `nil` response. `crud.upsert` success response is `{ rows = {}, metadata = ... }`, while `crud.upsert_many` is `{ metadata = ... }` (`res.rows == nil`) (see also #357).

So we have the following response alternatives for (at least partially) successful `noreturn` operation:
- `{ rows = {}, metadata = ... }`
- `{ metadata = ... }`
- `{}`
- `true`
- `nil`

(Bear in mind that in the case of the last three alternatives, we'll need to support noreturn for `upset` operations too.)

The main motivation of `noreturn` is to reduce the overhead on useless tuple transfer between router and storage. It seems that the solution on this side would be roughly the same for all of the alternatives. But there is the other point: to reduce the overhead on useless info transfer between the router and the connector (line `go-tarantool`, `tarantool-python`, `cartridge-java`). In this case, the latter -- `nil` -- seems better.

On the other hand, Receiving `nil, nil` in case of success may be a little confusing. But since `noreturn` is an optional one and the user of noreturn will know exactly what they expect, it seems fine.
