### ISSUE TITLE
Implement "IN" operator

### ISSUE THREAD

**Issue by akudiyar** [tarantool/crud#75]
Use case: customer wants to filter out tuples by values of an enum (e.g. filter orders by status). 

Proposed API variants:

a) New operator '[]' (or any other signature)
```
    crud.select('test_space', {{'[]', 'status', {"IN_PROGRESS", "NEW"}}})
```
b) Extend operator '=' for taking multiple values
```
    crud.select('test_space', {{'=', 'status', {"IN_PROGRESS", "NEW"}}})
```
This will be equivalent to having equal conditions combined with OR.

This operator should be available in all operations taking the conditions.

**Comment by knazarov** [comment]
This thing adds an additional nested loop. It will drastically increase the complexity of the explanation we have to give when the select reaches the hard limit of scanned tuples.

**Comment by akudiyar** [comment]
I think it may be done in one loop, just by adding a special comparator which does N comparations in a row instead of one.

**Comment by knazarov** [comment]
As I said, there are 2 problems with that:

- hidden costs of the select operation. If you pass an array of 1000 elements, your select complexity increases 1000x. And either you will hit an event loop very hard, or you'll need to stop when you reach a hard limit.
- when you reach a hard limit, you need to explain to the user why it happened. And to do that, you need a lot more complex way that will include nested explanations.

Your "in" operation will work well only if it's not a primary condition for the select.

The only benefits for you are that you don't have to do multiple calls. But the implementation cost is very high: you need to cover a lot of edge cases, write a significantly more complex explainer, and increase the complexity of the query planner so that it can handle cases when you pass the "in" operation that has sharding key as a condition.

Summary: that's why we ban all operations that have "OR" in their conditions. This is not an exception.

**Comment by Totktonada** [comment]
We discussed it with the product team and decided to don't implement it here. Sorry, Alexey.
