### ISSUE TITLE
Wait for master until a timeout

### ISSUE THREAD

**Issue by filonenko-mikhail** [tarantool/crud#95]
- Setup cartridge cluster with failover
- Setup separated crud-router and crud-storage
- Make a write load
- Switch master under load
- One time 

```
LuajitError: ...rk/starwars/.rocks/share/tarantool/crud/common/utils.lua:35: attempt to index field 'master' (a nil value)
```

**Comment by Totktonada** [comment]
It seems, it was crud-0.0.4. The relevant code is the following:

https://github.com/tarantool/crud/blob/1fa7ffc052852c98eea15ef4c48b4411554520dc/crud/common/utils.lua#L33-L37

The code remain unchanged since 0.0.4.

It seems logical that there is a time frame, when the old master is already demoted, but the new one is not promoted yet. Also I see that vshard contains 'whether there is a master?' [checks](https://github.com/tarantool/vshard/blob/93febbf368f381179ec56254b0c34f725120dcd8/vshard/replicaset.lua#L465-L477) that confirms my guess.

We should not lean on master presence unconditionally and should report a proper error if there is no master. The error should give a user hint that it is a transient error and the request can be safely retried.

BTW, crud has no autoretries / retry strategy settings?

**Comment by Totktonada** [comment]
BTW, as I see, vshard's call automatically waits for master (until a timeout). It seems, it would be good to use the same approach.

NB: Don't forget to substract time we waiting for a space from net.box request timeout.
